### ISSUE TITLE
Remove .git directories from fgsl and xraylib tarballs

### ISSUE THREAD

**Issue by jsberg-bnl** [bmad-sim/bmad-external-deps#18]
When doing build testing it a git tree, it is convenient to fully clean out the tree with `git clean -fdx`. The problem is that because the unpacked `fgsl` and `xraylib` tarballs have `.git` directories, the `fgsl` and `xraylib` directories are left untouched. So it would be good of those directories were removed from the distributed tarballs.

**Comment by DavidSagan** [comment]
@jsberg-bnl Done.
