### ISSUE TITLE
Upgrade gsl and fgsl to 2.6 and 1.5.0 respectively

### ISSUE THREAD

**Issue by jsberg-bnl** [bmad-sim/bmad-external-deps#3]
Right now you have 2.5 and 1.4.0. I see no reason not to upgrade, these have been used for the Conda build. As far as I can tell gsl-2.7 also works with fgsl 1.5.0 (I've successfully built that way), but fgsl doesn't advertise that compatibility, though that may very well be because development of fgsl has been abandoned.

**Comment by DavidSagan** [comment]
Upgraded.
